name: tecweb

x-environment: &default-env
  PUID: 1000
  PGID: 1000
  TZ: Europe/Rome

services:
  db:
    image: mariadb:11.8.3
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/mysql
      - ./setup-testenv.sql:/docker-entrypoint-initdb.d/1-setup.sql
      - ./database.sql:/docker-entrypoint-initdb.d/2-init.sql
    healthcheck:
      test:
        [
          "CMD",
          "healthcheck.sh",
          "--su=root",
          "--connect",
          "--innodb_initialized",
        ]
      start_period: 10s
    environment:
      <<: *default-env
      MARIADB_ROOT_PASSWORD: "${DB_PASSWORD}"
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin:latest
    restart: unless-stopped
    ports:
      - 8080:80
    links:
      - db:db
    environment:
      <<: *default-env

  php:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./src/:/var/www/html
    links:
      - db:db
    environment:
      MYSQL_HOST: db
      MYSQL_DATABASE: progetto
      MYSQL_USER: progetto
      MYSQL_PASSWORD: progetto

volumes:
  db_data:
